### ISSUE TITLE
[RFC] Change name of this extension.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/starter-kit#5]
This extension will come bundled with the pre-built composer installs, starting with 3.3. 

I'd like to change the name to something that sounds a little less like "this is here for the noobs". How about `bolt/configuration-notices`?

Since we'll start Bolt 3.3-beta soon, i'd like to get this changed soon, also. :-)

**Comment by CarsonF** [comment]
I thought this was supposed to be for more than configuration notices? I thought we'd also put other functionality here that will help out novices.

**Comment by bobdenotter** [comment]
This is for configuration notices, that you and Gawain didn't want in core. If there's going to be other novice-specific functionality that's better suited for an extension, i think it should be a separate extension.

**Comment by GawainLynch** [comment]
Yes, all for the rename and suggestion!

Only catch, there is a packagist entry, so we'll have to sweet talk Jordi to delete the old one :wink:

**Comment by bobdenotter** [comment]
I don't we need to do that. Packagist allows us to both "Abandon" as well as "Delete" a package, and It doesn't seem like it is used by anyone yet (because it's not actually operational), I think neither would cause any issues. 

I'm not clear on why this is a packagist package, and not a Bolt extension, though. Any particular reason for that?

**Comment by GawainLynch** [comment]
> Packagist allows us to both "Abandon" as well as "Delete" a package, 

Ah, that's new-ish then. 

> I'm not clear on why this is a packagist package

Because of when it needs to invoke.
